# Generated by Django 3.1.3 on 2020-12-01 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('audio_file', models.CharField(default=None, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('played', models.IntegerField(default=0)),
                ('success', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_number', models.IntegerField(default=0)),
                ('sentence', models.CharField(max_length=1000)),
                ('translation', models.CharField(max_length=1000, null=True)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('last_played', models.DateTimeField(null=True, verbose_name='last played')),
                ('played', models.IntegerField(default=0)),
                ('audio_file', models.CharField(default=None, max_length=300, null=True)),
                ('audio_start', models.FloatField(default=0.0, verbose_name='audio start')),
                ('audio_end', models.FloatField(default=0.0, verbose_name='audio end')),
                ('problem_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.problemset')),
            ],
        ),
    ]
