# Generated by Django 3.1.3 on 2020-12-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
