# Generated by Django 3.1.3 on 2020-12-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_auto_20201207_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='orig_start_end',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='setting',
            name='ignore_in_brackets',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='ignore_spacing',
            field=models.BooleanField(default=False),
        ),
    ]
