# Generated by Django 3.1.3 on 2020-12-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_auto_20201207_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='import_audio_time_added_after',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='setting',
            name='import_audio_time_added_before',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='setting',
            name='learning_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='record_stats',
            field=models.BooleanField(default=True),
        ),
    ]
