# Generated by Django 3.1.3 on 2021-01-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_auto_20201216_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscribeState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srt_file_path', models.CharField(max_length=200)),
                ('xml_file_path', models.CharField(max_length=200)),
                ('next_problem', models.IntegerField(default=0)),
            ],
        ),
    ]
