# Generated by Django 3.1.3 on 2021-03-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0009_transcribestate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcribestate',
            name='next_problem',
        ),
        migrations.RemoveField(
            model_name='transcribestate',
            name='srt_file_path',
        ),
        migrations.RemoveField(
            model_name='transcribestate',
            name='xml_file_path',
        ),
        migrations.AddField(
            model_name='transcribestate',
            name='skipped',
            field=models.IntegerField(default=0),
        ),
    ]
