# Generated by Django 3.1.3 on 2021-03-01 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_auto_20210228_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcribestate',
            old_name='skipped',
            new_name='next_problem',
        ),
    ]
