# Generated by Django 3.1.3 on 2021-03-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0011_auto_20210228_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcribestate',
            name='srt_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transcribestate',
            name='next_problem',
            field=models.IntegerField(default=1),
        ),
    ]
