# Generated by Django 3.2.4 on 2021-08-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0013_auto_20210829_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='one_word',
        ),
        migrations.AddField(
            model_name='setting',
            name='number_of_hidden_words',
            field=models.IntegerField(default=-1),
        ),
    ]
