# Generated by Django 3.2.4 on 2021-08-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0014_auto_20210829_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
