# Generated by Django 3.2.4 on 2021-08-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0015_problem_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='success',
            new_name='wrong',
        ),
    ]
