# Generated by Django 3.2.4 on 2021-08-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0016_rename_success_word_wrong'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='length_hint',
            field=models.BooleanField(default=False),
        ),
    ]
