# Generated by Django 3.2.4 on 2021-09-01 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0017_setting_length_hint'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='TrainingQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.problem')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.trainingqueue')),
            ],
        ),
    ]
