# Generated by Django 3.2.4 on 2021-09-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0019_trainingqueueitem_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingqueue',
            name='current_item_number',
            field=models.IntegerField(default=0),
        ),
    ]
