# Generated by Django 3.2.4 on 2021-09-03 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0020_trainingqueue_current_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingqueue',
            name='problem_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainer.problemset'),
        ),
    ]
