# Generated by Django 3.2.4 on 2021-09-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0021_trainingqueue_problem_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingqueue',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
