# Generated by Django 3.2.4 on 2022-03-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0023_setting_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='hide_translation',
            field=models.BooleanField(default=False),
        ),
    ]
