# Generated by Django 4.0.4 on 2022-04-20 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0025_alter_problem_last_played_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='fake_problem_number',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='problem_set',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainer.problem'),
        ),
    ]
