# Generated by Django 4.0.4 on 2022-04-22 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0026_remove_bookmark_fake_problem_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TranscribeState',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.problem'),
        ),
    ]
