# Generated by Django 4.0.4 on 2022-04-23 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0027_delete_transcribestate_alter_bookmark_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='audio_end',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='audio_start',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='orig_start_end',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='dark_mode',
        ),
        migrations.AlterField(
            model_name='problemset',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='trainingqueue',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this queue is in progress or finished.'),
        ),
        migrations.AlterField(
            model_name='trainingqueue',
            name='current_item_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainingqueue',
            name='problem_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.problemset'),
        ),
    ]
