# Generated by Django 4.0.4 on 2022-04-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0028_remove_problem_audio_end_remove_problem_audio_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingqueue',
            name='current_item_number',
            field=models.IntegerField(default=0),
        ),
    ]
